# Generated by Django 4.2.20 on 2025-04-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='spam_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='spam_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
